version: '3.8'
services:
  sveltekit:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: sveltekit-dev
    volumes:
      - .:/app
    restart: always
    command: npm run dev
    ports:
      - 5173:5173
    env_file:
      - .env
